import Navbar from '@/components/shared/navbar'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Fira_Code, Onest } from 'next/font/google'
import './globals.css'

// Fonts
const onest = Onest({ subsets: ['latin'], variable: '--onest' })
const firaCode = Fira_Code({ subsets: ['latin'], variable: '--fira_code' })

export const metadata: Metadata = {
	title: 'ChathubAi',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={cn('antialiased', onest.className, firaCode.variable)}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<section className="flex flex-col h-screen min-h-screen w-full overflow-auto scroll-smooth">
							<Navbar />
							<main className="flex flex-col flex-1">{children}</main>
						</section>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
