import { ThemeProvider } from '@/components/theme/theme-provider'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Fira_Code, Onest } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

// Fonts
const onest = Onest({ subsets: ['latin'], variable: '--onest' })
const firaCode = Fira_Code({
	subsets: ['latin'],
	variable: '--fira_code',
	preload: true,
	fallback: ['monospace'],
})

export const metadata: Metadata = {
	title: 'ChathubAi',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={cn('antialiased', onest.className, firaCode.variable)}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
